; version.asm
;
; Auto-generated by ZXVersion.exe
; On 27 Feb 2022 at 10:35

BuildNo                 macro()
                        db "7"
mend

BuildNoValue            equ "7"



BuildDate               macro()
                        db "27 Feb 2022"
mend

BuildDateValue          equ "27 Feb 2022"



BuildTime               macro()
                        db "10:35"
mend

BuildTimeValue          equ "10:35"



BuildTimeSecs           macro()
                        db "10:35:50"
mend

BuildTimeSecsValue      equ "10:35:50"
