; version.asm
;
; Auto-generated by ZXVersion.exe
; On 25 Feb 2022 at 14:36

BuildNo                 macro()
                        db "3"
mend

BuildNoValue            equ "3"



BuildDate               macro()
                        db "25 Feb 2022"
mend

BuildDateValue          equ "25 Feb 2022"



BuildTime               macro()
                        db "14:36"
mend

BuildTimeValue          equ "14:36"



BuildTimeSecs           macro()
                        db "14:36:10"
mend

BuildTimeSecsValue      equ "14:36:10"
