; version.asm
;
; Auto-generated by ZXVersion.exe
; On 28 Feb 2022 at 14:26

BuildNo                 macro()
                        db "9"
mend

BuildNoValue            equ "9"



BuildDate               macro()
                        db "28 Feb 2022"
mend

BuildDateValue          equ "28 Feb 2022"



BuildTime               macro()
                        db "14:26"
mend

BuildTimeValue          equ "14:26"



BuildTimeSecs           macro()
                        db "14:26:17"
mend

BuildTimeSecsValue      equ "14:26:17"
