; version.asm
;
; Auto-generated by ZXVersion.exe
; On 02 Mar 2022 at 18:22

BuildNo                 macro()
                        db "11"
mend

BuildNoValue            equ "11"



BuildDate               macro()
                        db "02 Mar 2022"
mend

BuildDateValue          equ "02 Mar 2022"



BuildTime               macro()
                        db "18:22"
mend

BuildTimeValue          equ "18:22"



BuildTimeSecs           macro()
                        db "18:22:45"
mend

BuildTimeSecsValue      equ "18:22:45"
