; version.asm
;
; Auto-generated by ZXVersion.exe
; On 01 Mar 2022 at 18:16

BuildNo                 macro()
                        db "10"
mend

BuildNoValue            equ "10"



BuildDate               macro()
                        db "01 Mar 2022"
mend

BuildDateValue          equ "01 Mar 2022"



BuildTime               macro()
                        db "18:16"
mend

BuildTimeValue          equ "18:16"



BuildTimeSecs           macro()
                        db "18:16:31"
mend

BuildTimeSecsValue      equ "18:16:31"
