; version.asm
;
; Auto-generated by ZXVersion.exe
; On 03 Mar 2022 at 20:10

BuildNo                 macro()
                        db "12"
mend

BuildNoValue            equ "12"



BuildDate               macro()
                        db "03 Mar 2022"
mend

BuildDateValue          equ "03 Mar 2022"



BuildTime               macro()
                        db "20:10"
mend

BuildTimeValue          equ "20:10"



BuildTimeSecs           macro()
                        db "20:10:01"
mend

BuildTimeSecsValue      equ "20:10:01"
